-- Migration number: 0022 	 2024-08-08T15:34:23.358Z
CREATE TABLE IF NOT EXISTS stats (
  id TEXT PRIMARY KEY UNIQUE NOT NULL,
  wins INTEGER DEFAULT 0,
  losses INTEGER DEFAULT 0,
  user_id TEXT UNIQUE NOT NULL,
  FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);
